### ISSUE TITLE
Document usage of PSR-17 factories

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authorization#14]
I merged #11 before we documented the change.

We need to detail how to use PSR-17 factories with this component — what changes users need to make, if any, etc.

**Comment by boesing** [comment]
I think its a good idea to document this when we do drop the old logic.
As of now, this just automagically works out-of-the-box when updating + not having a custom `ResponseInterface` factory declared in upstream project.

I did not document PSR-17 at all (even in the other packages I've merged earlier last year) since usually there is no need to change anything for upstream projects until we drop old logic.
And since mezzio does provide the `ResponseInterface` factory by-default, I am pretty sure that we did not documented the use of the callable factory in here as well, didn't we?
